"""Se crean los demas modelos

Revision ID: 1510221e8d4a
Revises: 5e7119f70038
Create Date: 2026-01-16 14:16:17.279289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1510221e8d4a'
down_revision: Union[str, Sequence[str], None] = '5e7119f70038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_is_active'), 'courses', ['is_active'], unique=False)
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=True)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_index(op.f('ix_lessons_title'), 'lessons', ['title'], unique=True)
    op.create_table('enrollments',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.create_index(op.f('ix_enrollments_completed'), 'enrollments', ['completed'], unique=False)
    op.create_index(op.f('ix_enrollments_grade'), 'enrollments', ['grade'], unique=False)
    op.create_table('user_lesson',
    sa.Column('student.id', sa.Integer(), nullable=False),
    sa.Column('course.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course.id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student.id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student.id', 'course.id')
    )
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_users_disabled'), table_name='users')
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.create_index(op.f('ix_users_disabled'), 'users', ['disabled'], unique=False)
    op.drop_column('users', 'is_active')
    op.drop_table('user_lesson')
    op.drop_index(op.f('ix_enrollments_grade'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_completed'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_lessons_title'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_index(op.f('ix_courses_is_active'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
