"""schema course-lesson modificado

Revision ID: 3c705a02e506
Revises: 2940426d7370
Create Date: 2026-01-18 20:18:28.601953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c705a02e506'
down_revision: Union[str, Sequence[str], None] = '2940426d7370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_lesson', sa.Column('lesson_id', sa.Integer(), nullable=False))
    op.add_column('course_lesson', sa.Column('course_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('course_lesson_ibfk_2'), 'course_lesson', type_='foreignkey')
    op.drop_constraint(op.f('course_lesson_ibfk_1'), 'course_lesson', type_='foreignkey')
    op.create_foreign_key(None, 'course_lesson', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'course_lesson', 'lesson', ['lesson_id'], ['id'])
    op.drop_column('course_lesson', 'course.id')
    op.drop_column('course_lesson', 'lesson.id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_lesson', sa.Column('lesson.id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('course_lesson', sa.Column('course.id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'course_lesson', type_='foreignkey')
    op.drop_constraint(None, 'course_lesson', type_='foreignkey')
    op.create_foreign_key(op.f('course_lesson_ibfk_1'), 'course_lesson', 'course', ['course.id'], ['id'])
    op.create_foreign_key(op.f('course_lesson_ibfk_2'), 'course_lesson', 'lesson', ['lesson.id'], ['id'])
    op.drop_column('course_lesson', 'course_id')
    op.drop_column('course_lesson', 'lesson_id')
    # ### end Alembic commands ###
