"""update users table2

Revision ID: 5e7119f70038
Revises: f45fbe5cdf54
Create Date: 2026-01-16 10:47:16.244281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7119f70038'
down_revision: Union[str, Sequence[str], None] = 'f45fbe5cdf54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_disabled'), 'users', ['disabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_disabled'), table_name='users')
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###
