"""Fix lesson table

Revision ID: def79a84898f
Revises: c3d9c826e20c
Create Date: 2026-01-21 08:38:50.349250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'def79a84898f'
down_revision: Union[str, Sequence[str], None] = 'c3d9c826e20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('professor_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('lesson_ibfk_1'), 'lesson', type_='foreignkey')
    op.create_foreign_key(None, 'lesson', 'user', ['professor_id'], ['id'])
    op.drop_column('lesson', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lesson', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_ibfk_1'), 'lesson', 'user', ['user_id'], ['id'])
    op.drop_column('lesson', 'professor_id')
    # ### end Alembic commands ###
